FROM node:19
WORKDIR /app
# Instala dependências para rodar scripts SQL e utilitários
RUN apt-get update && apt-get install -y \
    apt-utils 
COPY package*.json ./
COPY wait-for-it.sh /app/wait-for-it.sh
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
